refactor: social-icons color and size in main.css
shople-official/website pull request #4
Opened 2021-07-24 18:00 UTC by prashantk01

2021-07-24 19:21 UTC, saarthak08 requested changes

2021-07-24 19:21 UTC, saarthak08 commented on css/main.css
change these back to 36px

2021-07-25 04:54 UTC, prashantk01 commented on css/main.css
Okay Sir.

2021-07-25 05:00 UTC, saarthak08 submitted a review, later dismissed

2021-07-25 06:26 UTC, saarthak08 approved these changes

2021-07-25 06:31 UTC, Bhanups123 approved these changes

2021-07-25 06:31 UTC, merged